thedabfinder/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import *
from django.conf import settings
from django.conf.urls.static import static
from django.core.urlresolvers import reverse
admin.autodiscover()

urlpatterns = patterns('',
 url(r'^admin/', include(admin.site.urls)),
    (r'^robots\.txt$',  'pages.views.Robots'),
    (r'^$', 'pages.views.MainHomePage'),
    (r'^avatar/', include('avatar.urls')),
    (r'^tinymce/', include('tinymce.urls')),
    (r'^waxs/$', 'wax.views.WaxsAll'),
    (r'^dispensarys/$', 'wax.views.DispensarysAll'),
    (r'^waxs/(?P<waxslug>.*)/$', 'wax.views.SpecificWax'),
    (r'^dispensarys/(?P<dispensaryslug>.*)/$', 'wax.views.SpecificDispensary'),
    (r'^register/$', 'dabber.views.DabberRegistration'),
    (r'^login/$', 'dabber.views.LoginRequest'),
    (r'^logout/$', 'dabber.views.LogoutRequest'),
    (r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^resetpassword/$', 'django.contrib.auth.views.password_reset', {'post_reset_redirect' : '/reset/done/'}),
    (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
    (r'^profile/$', 'dabber.views.UserProfile'),
    (r'^captcha/', include('captcha.urls')),
    (r'^dabgifter/$', 'dabgifter.views.DabGifter'),
    (r'^review/', include('review.urls')),    
    (r'^tou/$',  'pages.views.Tou'),
    (r'^team/$',  'pages.views.Team'),
    (r'^ad/$',  'pages.views.Ad'),
    (r'^contact/$',  'pages.views.Contact'),
)      
if settings.DEBUG:
    urlpatterns += patterns('',
             (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes':True}),
         )

    urlpatterns += patterns('',
            (r'^medias/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
        )

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

try:
    from django.conf.urls import url, patterns
except:
    from django.conf.urls.defaults import url, patterns

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

dabber/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
#from annoying.fields import AutoOneToOneField
#from django.contrib.auth.models import AbstractBaseUser

# Create your models here.

class Dabber(models.Model):
        user            = models.OneToOneField(User, related_name="profile")
        birthday        = models.DateField()
        name            = models.CharField(max_length=100)
        email           = models.EmailField(max_length=100)
        dbr_pic         = models.ImageField(upload_to="images/dabberthumbs/", blank=True)	

        def __unicode__(self):
                return self.name


class UserProfile(models.Model):

        user            = models.OneToOneField(User, verbose_name=(u"user"), on_delete=models.CASCADE,)



        def __unicode__(self):
                return self.name

dabgifter/models.py
from django.db import models

# Create your models here.

wax/models.py
from django.db import models
from django.utils.encoding import smart_unicode
from djangoratings.fields import RatingField
from django.contrib.auth.models import User

# Create your models here.

WAX_TYPE = (
        ('E', 'Oil'),
        ('S', 'Shatter'),
        ('W', 'Wax'),
        ('O', 'Other',)
)

HIGH_TYPE = (
        ('ID', 'Indica'),
        ('IDH', 'Indica Dom. Hybrid'),
        ('HY', 'Hybrid'),
        ('SDH', 'Sativa Dom. Hybrid'),
        ('SV', 'Sativa'),
)
SOLVENT_TYPE = (
        ('B', 'Butane'),
        ('C', 'CO2'),
)


class Wax(models.Model):
        name            = models.CharField(max_length=200)
        slug            = models.SlugField(unique=True)
        dispensary      = models.ForeignKey('Dispensary')
        type            = models.CharField(max_length=1, choices=WAX_TYPE)
        high            = models.CharField(max_length=3, choices=HIGH_TYPE)
        solvent         = models.CharField(max_length=1, choices=SOLVENT_TYPE)
        pricepergram    = models.IntegerField(max_length=3, blank=False)
        description     = models.TextField(blank=True)
        wax_pic         = models.ImageField(upload_to="images/waxthumbs/")
	rating 		= RatingField(range=5) # 5 possible rating values, 1-5

        def __unicode__(self):
                return self.name

class Dispensary(models.Model):
        name            = models.CharField(max_length=200)
        slug            = models.SlugField(unique=True)
        city            = models.CharField(max_length=100)
        address         = models.CharField(max_length=200)
        phone           = models.BigIntegerField(max_length=11, blank=True)
        website         = models.CharField(max_length=200)
        email           = models.EmailField(blank=True)
        description     = models.TextField(blank=True)
	map_addr	= models.CharField(max_length=200, blank=True, default='', help_text='Please input like: City, Street Address')
        disp_pic        = models.ImageField(upload_to="images/dispthumbs")
	rating 		= RatingField(range=5) # 5 possible rating values, 1-5

        def __unicode__(self):
                return self.name

dabgifter/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from wax.models import Wax

@csrf_exempt
def DabGifter(request):
	waxs = Wax.objects.all().order_by('name')
	context = {'waxs': waxs}
        return render_to_response('dabgifter.html', context, context_instance=RequestContext(request))
		

templates/base.html
<html>
<head>
	

	<meta name="description" content="The online source for locating your next dab!">
	<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="/static/css/dabfinder.css">
	<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
	<link rel="icon"  type="image/png" href="/static/images/dflogo5.png">
	<link rel="apple-touch-icon" href="/static/images/dflogo5.png"/>
	<link rel="stylesheet" type="text/css" href="/static/css/addtohomescreen.css">
	<script src="/static/js/addtohomescreen.js"></script>
	<script> addToHomescreen(); </script>
	<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
	{% block extrahead %}
	{% endblock %}
	
</head>
<body><script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1544590149131336',
      xfbml      : true,
      version    : 'v2.2'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<script> addToHomescreen(); </script>

{% load avatar_tags %}
<div class="row">
<div id="pageContainer">


    



	    

        <nav class="navbar navbar-default  col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 col-xs-12" role="navigation" style="background-color: rgba(0, 0, 0, 0.9)">

  <div class="container">
     
      <a class="navbar-brand" href="/"><img src="/static/images/dflogo4.png" width="75" height="50" /></a>
    
    
        <font size="4">
        {% if user.is_authenticated %}
                 
            <b><a href="/profile/">Profile</a></b> .   
           <b> <a href="/logout/">Logout {% avatar user 55 %}</a></b>&nbsp&nbsp&nbsp&nbsp 
	  {% else %}
             
            <b><a href="/login/">Login</a></b> . 
           <b><a href="/register/">Sign Up</a></b>&nbsp&nbsp&nbsp&nbsp


        {% endif %}

        </font>
    
  </div><!-- /.container-fluid -->
 
</nav>
	
<br /><br /><br /><br />

        
	{% block content %}


	{% endblock %}
<!-- Social Footer, Colour Matching Icons -->
<!-- Include Font Awesome Stylesheet in Header -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<!-- // -->
<div class="container img-responsive">
         	<center>
	            <a href="https://twitter.com/DabFinder"><i id="social" class="fa fa-twitter-square fa-3x"></i></a>
	            <a href="https://www.facebook.com/profile.php?id=100008618432189"><i id="social" class="fa fa-facebook-square fa-3x social-fb"></i></a>
	            <a href="mailto:barry5hallsack@gmail.com"><i id="social" class="fa fa-envelope-square fa-3x"></i></a>
		</center>

</div>
<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>
    <hr>
</div>
<div>
        <center>
       <a href="http://www.wrapsprint.com"> <img src="/static/images/wraps_banner.gif" class="img-responsive"></a>
        <center>
        </div>
        
</div>
</div>

<script src="/media/js/bootstarp.js">
<script src="/media/js/jquery.js">
<script src="/media/js/df.js">


</body>
      
</html>

templates/dabgifter.html
<html>
<head>
<title>THE DAB GIFTER</title>
        <meta name="description" content="The online source for locating your next dab!">
        <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.js" type="text/javascript"></script>
<style>
#fb_header{background:   url(/static/images/sativa.png) repeat scroll top center #FFFFFF;height:200px; width:auto;}
#fb_waxs{background: url(/static/images/sativa.png) repeat top center #000000;width:auto;}
.wax_ul{background: url(/static/images/shelf2.png) no-repeat scroll 0 118px transparent;margin:-50;padding:105 55px;width:1000px;height:300px;list-style:none outside none;}
.wax_ul li{float:left;text-align:center;width:100px;margin-left:45px; color: #FFFFFF}
</style>	
</head>
<body>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1544590149131336',
      xfbml      : true,
      version    : 'v2.2'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
    
<div class="row">
<div id="fb_container">
        <div id="fb_header"><center>
                <img src="/static/images/dflogo1.png" height="300" width="600"class="img-responsive" /></center>
        </div>
	
        <div id="fb_waxs">
               <center> <ul class="wax_ul">
                {% for wax in waxs %}
                        <li>
                        <a href="/waxs/{{ wax.slug }}/"><img src="{{ wax.wax_pic.url }}" width="100" height="100" class="img-circle" ></a>
                        <p><b>{{ wax.name }}</b></p>
                        </li>
                {% if forloop.counter|divisibleby:"6" and not forloop.last %}</ul><ul class="wax_ul">{% endif %}
                {% endfor %}
                </ul></center>
        </div>
</div>
</div>
</body>
</html>
	

templates/dispensarysall.html
{% extends 'base.html' %}
        {% block extrahead %}
                <title>Dabspensarys</title>
        {% endblock %}
{% block content %}
{% if user.is_authenticated %}
	

	
		         <div class="row">

        <div class="col-md-12 toppad" >
	<div class="panel panel-info" style="background-color: rgba(0, 0, 0, 0.9)" >
            <div class="panel-heading">
			<center><b>Dabspensarys</b></center>
            </div>

               <div class="panel-body">

		{% for dispensary in dispensarys %}
		<div class="row">	
		<div class="col-md-12" align="left"><a href="/waxs/"><a href="/dispensarys/{{ dispensary.slug }}/"><img src="{{ dispensary.disp_pic.url }}"  width="75" height="75" class="img-circle" />
			<button type="button" class="btn btn-info btn-con">{{ dispensary }}</button></a>
		{% endfor %}
            </div>
	   </div>	
	 </div>
	</div>
                       
	<div id="nav_bottom" class-""toppad>
                <center><p><a href="/waxs/"><button type="button" class="btn btn-primary">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp DABS&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</button></a>
			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp; <a href="/dispensarys/"><button type="button" class="btn btn-primary">DISPENSARYS</button></a></p></center>
        </div>
	</div>	
{% else %}
<img src="/static/images/ahahah.gif" width='468px'>
<center><h3><p>Please <a href="/login/">Login</a> to view this page</p></h3></center>
{% endif %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
        {% block extrahead %}
		<title>Welcome to The Dab Finder!!!</title>
        {% endblock %}
{% block content  %}
	<div id="home_copy">
		{{ homepage.homecopy | safe }}
	<div id="tweets_div" style="background-color: rgba(0, 0, 0, 0.9); font-size: 10; color: #FFFFFF">
	<p class="tweettime">Newest tweets</p>
	<ul id="home_tweets">
                {% for tweet in tweets.tweets|slice:":5" %}
	
                <li class="tweettext">{{ tweet.status  }}</li>
                <li class="tweettime">{{ tweet.date }}</li>
	  
              {% endfor %}
        </ul>
	</div>
	{% if user.is_authenticated %}
	<div id="nav_bottom">
                <center><p><a href="/waxs/"><button type="button" class="btn btn-primary">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp DABS&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                        </button></a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp;
        <a href="/dispensarys/"><button type="button" class="btn btn-primary">DISPENSARYS</button></a></p></center>
	</div>{% else %} {% endif %}
	<div>
        
	
{% endblock  %}

templates/login.html
{% extends "base.html" %}
{% block content %}
<center>
<h1>Login to Dab Finder</h1>
<form action="" method="post">
{% csrf_token %}
{% if form.errors %}<p>Please correct the following fields:</p>{% endif %}
<div class="register_div">
        {% if form.username.errors %}<p class="error">{{ form.username.errors }}</p>{% endif %}
        <p><label for="username"{% if form.username.errors %} class="error"{% endif %}>Username:</label></p>
        <p>{{ form.username }}</p>
</div>
<div class="register_div">
        {% if form.password.errors %}<p class="error">{{ form.password.errors }}</p>{% endif %}
        <p><label for="password"{% if form.password.errors %} class="error"{% endif %}>Password:</label></p>
        <p>{{ form.password }}</p>
</div>
<p><input type="submit" alt="register" /></p>
</form>

</center>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
        {% block extrahead %}
		<title>DABBER PROFILE</title>
        {% endblock %}
{% block content %}
	<div id="profile">
	
		{% load avatar_tags %}	
		



      <div class="row">
      
        <div class="col-md-12 toppad" >
   
   
          <div class="panel panel-info"  style="background-color: rgba(0, 0, 0, 0.9)">
            <div class="panel-heading">
              <h3 class="panel-title">{{ dabber }}</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center" > {% avatar user 65 %}</div>
                
                <!--<div class="col-xs-10 col-sm-10 hidden-md hidden-lg"><br>
                  <dl>
                    <dt>DEPARTMENT:</dt>
                    <dd>Administrator</dd>
                    <dt>HIRE DATE</dt>
                    <dd>11/12/2013</dd>
                    <dt>DATE OF BIRTH</dt>
                       <dd>11/12/2013</dd>
                    <dt>GENDER</dt>
                    <dd>Male</dd>
                  </dl>
                </div>-->
                <div class=" col-md-9 col-lg-9"> 
                  <table class="table table-user-information tweettext">
                    <tbody>
                      <tr>
                        <td>Dabber:</td>
                        <td>{{ user.profile.name }}</td>
                      </tr>
                      <tr>
                        <td>Join date:</td>
                        <td>{{ user.date_joined }}</td>
                      </tr>
                      <tr>
                        <td>Date of Birth:</td>
                        <td>{{ user.profile.birthday }}</td>
                      </tr>
                   
                         <tr>
                             
                        <td>Email:</td>
                        <td>{{ user.email }}</td>
                      </tr>
                      <tr>
                        <td></td>
                        <td></td>
                      </tr>
        
                      </tr>
                     
                    </tbody>
                  </table>
                  
                  <a href="{% url 'avatar_change' %}" class="btn btn-primary">Change your avatar</a>
                </div>
              </div>
            </div>
                 <div class="panel-footer" style="background-color: rgba(0, 0, 0, 0.5)"  >
                        

                    </div>
            
          </div>
        </div>
      </div>
    





	
        <div id="nav_bottom">
                <center><p><a href="/waxs/"><button type="button" class="btn btn-primary">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp DABS&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</button></a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp; 
		<a href="/dispensarys/"><button type="button" class="btn btn-primary">DISPENSARYS</button></a></p></center>
        </div>
</div>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block extrahead %}
        <script src="/static/js/jquery.js" type="text/javascript"></script>
        <script src="/static/js/jquery-ui.js" type="text/javascript"></script>
        <script>
        $(function() {
                $( "#id_birthday" ).datepicker();
        });
        </script>
	 <link rel="stylesheet" type="text/css" href="/static/css/jquery-ui.css">
	 <link rel="stylesheet" type="text/css" href="/static/css/jquery-ui.theme.css">
{% endblock %}
{% block content %}
<center><h2>Register for The Dab Finder</h2></center>
<form action="" method="post">
{% csrf_token %}
{% if form.errors %}<p>Please correct the following fields:</p>{% endif %}
<div class="register_div" align="center">
        {% if form.username.errors %}<p class="error">{{ form.username.errors }}</p>{% endif %}
        <p><label for="username"{% if form.username.errors %} class="error"{% endif %}>Username:</label></p>
        <p>{{ form.username }}</p>
</div>
<div class="register_div"  align="center">
        {% if form.email.errors %}<p class="error">{{ form.email.errors }}</p>{% endif %}
        <p><label for="email"{% if form.email.errors %} class="error"{% endif %}>Email:</label></p>
        <p>{{ form.email }}</p>
</div>
<div class="register_div"  align="center">
        {% if form.password.errors %}<p class="error">{{ form.password.errors }}</p>{% endif %}
        <p><label for="password"{% if form.password.errors %} class="error"{% endif %}>Password:</label></p>
        <p>{{ form.password }}</p>
</div>
<div class="register_div"  align="center">
        {% if form.password1.errors %}<p class="error">{{ form.password1.errors }}</p>{% endif %}
        <p><label for="password1"{% if form.password1.errors %} class="error"{% endif %}>Verify Password:</label></p>
        <p>{{ form.password1 }}</p>
</div>
<div class="register_div"  align="center">
        {% if form.birthday.errors %}<p class="error">{{ form.birthday.errors }}</p>{% endif %}
        <p><label for="birthday"{% if form.birthday.errors %} class="error"{% endif %}>Birthday:</label></p>
        <p>{{ form.birthday }}</p>
</div>
<div class="register_div"  align="center">
        {% if form.captcha.errors %}<p class="error">{{ form.captcha.errors }}</p>{% endif %}
        <p><label for="captcha"{% if form.captcha.errors %} class="error"{% endif %}>CAPTCHA:</label></p>
        <p>{{ form.captcha }}</p>
</div>

<center><p><input type="submit" alt="register" /></p></center>
</form>
{% endblock %}

templates/singlewax.html
{% extends 'base.html' %}
        {% block extrahead %}
                <title>Dab Description</title>
        {% endblock %}
{% block content  %}
{% if user.is_authenticated %}
{% load avatar_tags %}
	
 <div class="row">

        <div class=" col-md-12  toppad" >


          <div class="panel panel-info" style="background-color: rgba(0, 0, 0, 0.9)" >
            <div class="panel-heading  tweettext">
              <h3 class="panel-title">DABSCRIPTION</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="DAB Pic" src="{{ wax.wax_pic.url }}" width="100" height="100" class="img-circle"> </div>

                <!--<div class="col-xs-9 col-sm-9 hidden-md hidden-lg"> <br>
                  <dl>
                    <dt>DAB NAME:</dt>
                    <dd>{{ wax }}</dd>
                    <dt>TYPE:</dt>
                    <dd>{{ wax.get_type_display }}</dd>
                    <dt>SOLVENT:</dt>
                       <dd>{{ wax.get_solvent_display }}</dd>
                    <dt>PPG:</dt>
                       <dd>${{ wax.pricepergram }}</dd>
                    <dt>DABSPENSARY:</dt>
                    <dd>><a href="/dispensarys/{{ wax.dispensary.slug }}/">{{ wax.dispensary }}</a><</dd>
		    <dt>HIGH:</dt>
                       <dd>{{ wax.get_high_display }}</dd>	
                  </dl>
                </div>-->
                <div class=" col-md-9 col-lg-9 ">
                  <table class="table table-user-information tweettext">
                    <tbody>
                      <tr>
                        <td>DAB NAME:</td>
                        <td><b>{{ wax }}</b></td>
                      </tr>
                      <tr>
                        <td>TYPE:</td>
                        <td><b>{{ wax.get_type_display }}</b></td>
                      </tr>
                      <tr>
                        <td>SOLVENT:</td>
                        <td>{{ wax.get_solvent_display }}</b></a></td>
                      </tr>
                         <tr>
                             <tr>
                        <td>DABSPENSARY:</td>
                        <td><b><a href="/dispensarys/{{ wax.dispensary.slug }}/">{{ wax.dispensary }}</a></b></td>
                      </tr>
                        <tr>
                        <td>HIGH:</td>
                        <td><b>{{ wax.get_high_display }}</b></td>
                      </tr>
		     <tr>
                        <td>PPG:</td>
                        <td><b>${{ wax.pricepergram }}</b></td>

                      </tr>
                     <tr>
                        <td>INFO:</td>
                        <td><b>{{ wax.description }}</b></td>

                      </tr>
                    </tbody>
                  </table>
		<center>
		       
            </div>
              </div>

         <div class="panel-footer" style="background-color: rgba(0, 0, 0, 0.5)" >
               <img src="{{ wax.wax_pic.url }}" height="" width="" class="img-responsive" />
		                         {% load avatar_tags %} {% load review_tags %}
		     <div class="reviews tweettext">
			<h3>Staff Reviews:</h3>
			<hr />
                        {% get_reviews wax as reviews %}
                        {% for review in reviews %}
                          <p>
                        {% avatar review.user 65%}
                        {% if review.content %}
                        {{ review.content|truncatewords:'70' }}  - <font size=1> {{ review.user }} </font>
			<hr />
                        {% else %}
                        Reviewed without description.
                        {% endif %}{% endfor %}
			</p>
		    </div>
	<div id="nav_bottom">
                <center><p><a href="/waxs/"><button type="button" class="btn btn-primary">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp DABS&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                        </button></a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp;
        <a href="/dispensarys/"><button type="button" class="btn btn-primary">DISPENSARYS</button></a></p></center>
        </div>

  </div>
 </div>


{% else %}
<img src="/static/images/ahahah.gif" width='490px'>
<center><h3><p>Please <a href="/login/">Login</a> to view this page</p></h3></center>
{% endif %}
{% endblock %}

templates/waxsall.html
{% extends 'base.html' %}
        {% block extrahead %}
                <title>Find Your Dab</title>
        {% endblock %}
{% block content %}
{% if user.is_authenticated %}

                         



                         <div class="row">

        <div class="col-md-12 toppad" >
        <div class="panel panel-info" style="background-color: rgba(0, 0, 0, 0.9)" >
            <div class="panel-heading tweettext">
                        <center><b>Find Your Dab</b></center>
            </div>

               <div class="panel-body">

                {% for wax in waxs %}
		<div class="row">
                <div class="col-md-12" align="left"><a href="/waxs/"><a href="/waxs/{{ wax.slug }}/"><img src="{{ wax.wax_pic.url }}" height="75" width="75" class="img-circle" />
                         <button type="button" class="btn btn-success btn-cons">{{ wax }} ${{ wax.pricepergram }}/gr</button></a></b><a href="/dispensarys/{{ wax.dispensary.slug }}/">
				<button type="button" class="btn btn-info btn-cons"> &#10010;</button></a>
    
                {% endfor %}
            </div>
           </div>
         </div>
    	</div>


        

        <div id="nav_bottom" class-"toppad">
                <center><p><a href="/waxs/"><button type="button" class="btn btn-primary">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp DABS&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</button></a>
                        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp; <a href="/dispensarys/"><button type="button" class="btn btn-primary">DISPENSARYS</button></a></p></center>
        </div>
	


{% else %}
<img src="/static/images/ahahah.gif" width='490px'>
<center><h3><p>Please <a href="/login/">Login</a> to view this page</p></h3></center>
{% endif %}

{% endblock %}